### ISSUE TITLE
Example of creating a new task available?

### ISSUE THREAD

**Issue by orangethirty** [blimpllc/blimp-python#1]
I'm looking into your API to integrate it with a django CRM project. For evert lead generated by the website, I'd like to create a new task in a Blimp project. Looked around your docs, and I see there is a method available to create the task. Though I did not find an example of how to use it. May you share some examples? Including (but not limited to) the JSON structure the API expects.

Thank you. (:

**Comment by jpadilla** [comment]
Hey @orangethirty that sounds interesting. Here's an example of how to create a task. The required fields are **title**, and **goal**. You could assign the task to a user while creating it by passing the **assigned_to** field. Let me know if you need any further help. I'm glad to help out.

``` python
import blimp

username = ''
api_key = ''
app_id = ''
app_secret = ''

api = blimp.Client(username, api_key, app_id, app_secret)

# goal and title are required, assigned_to is optional
data = {
    'goal': '/api/v2/goal/1/',
    'title': 'Example of how to create a task',
    # 'assigned_to': '/api/v2/user/1/'
}

task = api.task.create(data)
print task

```

**Comment by orangethirty** [comment]
Thank you. This is pretty straightforward. I'll update you with progress (through twitter). (:
